# Site
name: "Bon Appétit"
title: "Bon Appétit"
description: "胃口不小心太好，猛吃的故事"
logo: 'assets/images/logo.png'
favicon: 'assets/images/logo.png'
baseurl: /
google_analytics: 'G-CVZG14TSCT'
disqus: 'lilacsage'
mailchimp-list: 'none'
include: ["_pages"]
permalink: /:title/
email: thelilacsage@gmail.com

# Authors
authors:
  lilac:
    name: Lilac
    display_name: Lilac
    avatar: 'assets/images/logo.png'
    email: thelilacsage@gmail.com
    # web:
    # twitter:
    description: "Author"
  babe:
    name: Babe
    display_name: Babe
    avatar: 'assets/images/logo.png'
    email:
    # web:
    # twitter:
    description: "Placeholder"

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
  - jekyll-figure
  - jemoji

# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  comments: true
  permalinks:
    category: '/category/:name/'

# Pagination
paginate: 6
paginate_path: /page:num/

# Other
highlighter: none
markdown: kramdown
kramdown:
   syntax_highlighter_opts:
      disable : true



# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
adsense-data-ad-client: "ca-pub-3412143450191416"
adsense-data-ad-slot: "1363087678"

# Lazy Images ("enabled" or "disabled")
lazyimages: "disabled"

# Post Author Box ("enabled" or "disabled")
authorbox: "enabled"

# Sass
sass:
  sass_dir: _sass
  style: compressed

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
